CCFLAGS =  -std=c++11 -O3 -fPIC  -luWS -lindicator -lssl -lz -lpthread -lcjson -Wunused-result
LIBPATH = -L/home/riddle/uws -L ./ -L ../../u/lib -L ../lib/seetalib-1.0.0/lib

ALLLIBS = -luBEE -luWS -lssl -lz -lpthread -lcjson -lpq -luuid -lsee_talib -lindicator -lApiClient

LDFLAGS += -L/usr/local/lib `pkg-config --libs protobuf grpc++ grpc`\
           -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed\
           -ldl

CTPLIBS:= ../ctp/thostmduserapi.so \
        ../ctp/thosttraderapi.so

EXE = ../../u/exe/

SRC = ./
INC = ../inc/
OBJ = ../../u/obj/

INCS = -I ../inc -I ./indicator -I ../indicator \
       -I ../lib/seetalib-1.0.0/include \
       -I /usr/include \
       -I /usr/local/include \
	   -I /usr/include/postgresql

default:  exes

exes: $(EXE)t1.x \
	$(EXE)main.x \
	$(EXE)mnf.x

MAINOBJS:= \
	$(OBJ)Main.o \
	$(OBJ)Index.o

T1OBJS:= \
	$(OBJ)t1.o \
	$(OBJ)Index.o

MNFOBJS:= \
	$(OBJ)mnf.o \
	$(OBJ)Index.o

$(EXE)main.x: $(MAINOBJS)
	$(CXX) $(CCFLAGS) -o $(EXE)main.x $(MAINOBJS) $(LIBPATH) $(ALLLIBS) $(CTPLIBS) $(LDFLAGS)

$(EXE)t1.x: $(T1OBJS)
	$(CXX) $(CCFLAGS) -o $(EXE)t1.x $(T1OBJS) $(LIBPATH) $(ALLLIBS) $(CTPLIBS) $(LDFLAGS)

$(EXE)mnf.x: $(MNFOBJS)
	$(CXX) $(CCFLAGS) -o $(EXE)mnf.x $(MNFOBJS) $(LIBPATH) $(ALLLIBS) $(CTPLIBS) $(LDFLAGS)

$(OBJ)Main.o: $(SRC)Main.cpp
	$(CXX) -c $(CCFLAGS) $(INCS) -o $(OBJ)Main.o  $(SRC)Main.cpp

$(OBJ)Index.o: $(SRC)Index.cpp
	$(CXX) -c $(CCFLAGS) $(INCS) -o $(OBJ)Index.o  $(SRC)Index.cpp

$(OBJ)t1.o: $(SRC)t1.cpp
	$(CXX) -c $(CCFLAGS) $(INCS) -o $(OBJ)t1.o  $(SRC)t1.cpp

$(OBJ)mnf.o: $(SRC)mnf.cpp
	$(CXX) -c $(CCFLAGS) $(INCS) -o $(OBJ)mnf.o  $(SRC)mnf.cpp
